Using attribute to specify language to highlight.js
MyNihongo/MudBlazor.Markdown pull request #103
Opened 2022-07-06 22:28 UTC by Lukazoid

Fixes #102

2022-07-08 13:22 UTC, MihailsKuzmins requested changes

2022-07-08 16:59 UTC, Lukazoid commented on src/MudBlazor.Markdown/Components/MudCodeHighlight.razor.cs
> +		builder.AddAttribute(i++, "class", $"language-{Language}");
Added in e4b06926277ca7118d486df2016ef125d9eaa5d7

2022-07-09 02:13 UTC, MihailsKuzmins approved these changes

2022-07-09 02:21 UTC, MihailsKuzmins commented
OK, the code looks good, but now there are three failing tests. Please run the tests locally and fix them!
Please make sure to add a unit test where `Language` is null or empty to cover the new functionality.
```cs
[Fact]
public void RenderCodeBlockWithoutLanguage()
{
	const string value =
@"```
public bool IsMudBlazorCool()
{
	return true;
}
```";

	const string expected = ".....";

	using var fixture = CreateFixture(value);
	fixture.MarkupMatches(expected);
}
```

2022-07-09 02:22 UTC, MihailsKuzmins requested changes
OK, the code looks good, but now there are three failing tests. Please run the tests locally and fix them!
Please make sure to add a unit test where `Language` is null or empty to cover the new functionality.
```cs
[Fact]
public void RenderCodeBlockWithoutLanguage()
{
	const string value =
@"```
public bool IsMudBlazorCool()
{
	return true;
}
```";

	const string expected = ".....";

	using var fixture = CreateFixture(value);
	fixture.MarkupMatches(expected);
}
```

2022-07-09 12:24 UTC, MihailsKuzmins approved these changes

2022-07-09 12:24 UTC, merged