added property 'style' to the image tag
MyNihongo/MudBlazor.Markdown pull request #168
Opened 2023-05-14 23:22 UTC by cabiste69

This should fix images getting out of the mudPaper's boundaries and it's how github does it

### examples: 

**before:**
- on desktop
![before1](https://github.com/MyNihongo/MudBlazor.Markdown/assets/55938130/caf61e2d-bb6d-42cc-9c2c-91e7b2a7353f)
- on mobile
![before2](https://github.com/MyNihongo/MudBlazor.Markdown/assets/55938130/430edee7-e6cc-4c8b-b065-b64ed623f7b5)

**After:**
- on desktop
![after1](https://github.com/MyNihongo/MudBlazor.Markdown/assets/55938130/44e8c8f9-d17f-47c9-a5b8-3ee5ff878398)
- on mobile
![after2](https://github.com/MyNihongo/MudBlazor.Markdown/assets/55938130/def8fc3d-4229-4817-9f32-7e1301a7762c)

2023-05-16 01:12 UTC, my-nihongo requested changes
I see, thanks for the MR. I believe that rendering of `<image>` is not implemented correctly. It misses some MudBlazor classes like `mud-image object-fill object-center mud-elevation-25 rounded-lg` (or something similar).

May I ask you to change the render code to (MudMarkdown.razor.cs line 269)
```cs
builder.OpenComponent<MudImage>(_elementIndex++);
builder.AddAttribute(_elementIndex++, nameof(MudImage.Src), url);
builder.AddAttribute(_elementIndex++, nameof(MudImage.Alt), string.Join(null, alt));
builder.CloseComponent();
```

After that you could try to play with various properties as it is described in the [documentation](https://mudblazor.com/components/image) to make it work for you.

2023-05-18 01:17 UTC, cabiste69 commented
sorry i didn't understand you properly, do you want me to cancel the PR or try to improve it and commit again?

2023-05-18 02:17 UTC, MihailsKuzmins commented
Improve. Maybe using `<MudImage>` will solve your problem by default without adding the style block.

2023-05-27 12:24 UTC, my-nihongo commented
Closed by #178

2023-05-27 12:24 UTC, closed without merging