Add strikethrough support
MyNihongo/MudBlazor.Markdown pull request #280
Opened 2024-11-18 18:33 UTC by NALStudio

|Before|After|
|-------|------|
|![before](https://github.com/user-attachments/assets/f3c6de3f-9a3e-42a2-a97b-979a4ee81ec4)|![after](https://github.com/user-attachments/assets/aa33075d-eaf3-401b-8ee8-3cc086850dfc)|

This is a simple change, but the code might need more refactoring as currently if any invalid emphasis is detected, the entire text rendering is skipped. I'd like to have it so that invalid/unsupported emphasis is drawn with a red background so that it is clearer to the user when errors happen instead of just hiding the text completely. That feature was out of the scope of this PR, though I can add it in a separate PR if this idea sounds like something worth pursuing.

2024-11-20 02:34 UTC, MihailsKuzmins commented
Thanks for the PR.

> if any invalid emphasis is detected, the entire text rendering is skipped. I'd like to have it so that invalid/unsupported emphasis is drawn with a red background so that it is clearer to the user when errors happen instead of just hiding the text completely. 

About your comment, I think the approach is valid, but it will probably be better to keep the original text as it is. The same approach with the tables in https://github.com/MyNihongo/MudBlazor.Markdown/pull/276

2024-11-20 02:41 UTC, MihailsKuzmins requested changes

2024-11-20 02:41 UTC, MihailsKuzmins commented on samples/MudBlazor.Markdown.Core/sample.md
> +Some regular text. *Text in italics*, **text in bold.** and ~~text in strikethrough~~.
Could you please remove `.`?  
`**text in bold.**` -> `**text in bold**`

2024-11-20 02:41 UTC, MihailsKuzmins commented on src/MudBlazor.Markdown/Extensions/EmphasisInlineEx.cs
> +			strike = "del";
Could you please put all three constants on the same line? And rename `strike` to `strikethrough`?

```cs
const string italics = "i", bold = "b", strikethrough = "del";
```

2024-11-20 02:41 UTC, MihailsKuzmins commented on tests/MudBlazor.Markdown.Tests/MarkdownComponentTests/MarkdownComponentShould.cs
> +	public void RenderCodeItalicBoldAndStrike()
Could you please rename the test method name?  
※ If we keep adding more elements to this test, the name length will increase.

`RenderCodeItalicBoldAndStrike` -> `RenderEmphasisElements`

2024-11-20 13:00 UTC, NALStudio commented
Requested changes made :)

2024-11-21 02:34 UTC, MihailsKuzmins approved these changes

2024-11-21 02:40 UTC, merged